# Generated by Django 5.2 on 2025-05-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_taskstatus_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriptios',
            new_name='description',
        ),
    ]
